### ISSUE TITLE
Dependencies in pom

### ISSUE THREAD

**Issue by tischi** [tischi/imagej-utils#25]
@K-Meech 
There are tons of dependencies in the pom, which I think do not need to be there.
I will try to remove them.
Did you by chance add some?

**Comment by tischi** [comment]
@K-Meech 

I made the changes.

Could you please 
- pull the current master and see whether that works for you?
- mvn clean install 
- check that mobie-beta and your em tool are working with this
    - don't forget to have 0.5.5-SNAPSHOT as the version in the respective poms

If that works for you, I would cut a release (0.5.5) because I may want to depend on a newer version of bigdataviewer from then on, which will cause some dependency issues (so 0.5.5 could be the last version with the old bdv).

**Comment by K-Meech** [comment]
I don't think I added anything to the pom.
I tried out the current master with both mobie-beta / my em plugin, and both seem to be working well.
So go ahead!

**Comment by tischi** [comment]
ok.
FYI: I will update MoBIE-beta today, because of this: https://github.com/mobie/mobie-viewer-fiji/issues/137
