### ISSUE TITLE
Add .mhd writing to BdvRealSourceToVoxelImageExporter

### ISSUE THREAD

**Issue by K-Meech** [tischi/imagej-utils#32]
@tischi I'm looking at adding the option to write to mhd here: https://github.com/tischi/imagej-utils/blob/master/src/main/java/de/embl/cba/bdv/utils/export/BdvRealSourceToVoxelImageExporter.java#L81 

You have this code in your elastix wrapper - https://github.com/embl-cba/elastixWrapper/blob/master/src/main/java/de/embl/cba/elastixwrapper/metaimage/MetaImage_Writer.java#L207 

Could it possibly be moved to imagej-utils?

**Comment by tischi** [comment]
makes sense.

For now, you could just already add the code to imagej-utils and then I could change the elastix wrapper to depend on it at some later point.

Could you make an issue in the elastixWrapper repo to remind me?

**Comment by K-Meech** [comment]
Sure - will do!

**Comment by K-Meech** [comment]
This will move to https://github.com/embl-cba/metaimage-io
